"""initial core schema

Revision ID: 20260909_0001
Revises: 
Create Date: 2026-09-09 10:43:44.351825
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '20260909_0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_sources',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('base_url', sa.String(length=1000), nullable=False),
    sa.Column('schedule', sa.String(length=120), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_sources')),
    sa.UniqueConstraint('name', name=op.f('uq_job_sources_name'))
    )
    op.create_table('job_tags',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_tags')),
    sa.UniqueConstraint('name', 'category', name=op.f('uq_job_tags_name'))
    )
    op.create_index(op.f('ix_job_tags_name'), 'job_tags', ['name'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('job_seeker', 'admin', name='user_role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('crawl_runs',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'partial', 'failed', name='crawl_run_status', native_enum=False), nullable=False),
    sa.Column('trigger', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_found', sa.Integer(), nullable=False),
    sa.Column('items_new', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('items_failed', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], name=op.f('fk_crawl_runs_source_id_job_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_crawl_runs'))
    )
    op.create_index(op.f('ix_crawl_runs_status'), 'crawl_runs', ['status'], unique=False)
    op.create_table('job_postings',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('salary_period', sa.String(length=30), nullable=True),
    sa.Column('education', sa.String(length=200), nullable=True),
    sa.Column('experience', sa.String(length=200), nullable=True),
    sa.Column('job_type', sa.String(length=80), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('apply_url', sa.String(length=2000), nullable=False),
    sa.Column('posted_at', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('dedup_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('salary_min IS NULL OR salary_max IS NULL OR salary_min <= salary_max', name=op.f('ck_job_postings_salary_range')),
    sa.ForeignKeyConstraint(['source_id'], ['job_sources.id'], name=op.f('fk_job_postings_source_id_job_sources'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_postings')),
    sa.UniqueConstraint('dedup_hash', name=op.f('uq_job_postings_dedup_hash')),
    sa.UniqueConstraint('source_id', 'external_id', name=op.f('uq_job_postings_source_id'))
    )
    op.create_index(op.f('ix_job_postings_city'), 'job_postings', ['city'], unique=False)
    op.create_index('ix_job_postings_city_type_deadline', 'job_postings', ['city', 'job_type', 'deadline'], unique=False)
    op.create_index(op.f('ix_job_postings_company'), 'job_postings', ['company'], unique=False)
    op.create_index(op.f('ix_job_postings_deadline'), 'job_postings', ['deadline'], unique=False)
    op.create_index(op.f('ix_job_postings_job_type'), 'job_postings', ['job_type'], unique=False)
    op.create_index(op.f('ix_job_postings_posted_at'), 'job_postings', ['posted_at'], unique=False)
    op.create_index('ix_job_postings_salary', 'job_postings', ['salary_min', 'salary_max'], unique=False)
    op.create_index(op.f('ix_job_postings_status'), 'job_postings', ['status'], unique=False)
    op.create_index(op.f('ix_job_postings_title'), 'job_postings', ['title'], unique=False)
    op.create_table('user_profiles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('education', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('links', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_table('application_forms',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('template_version', sa.String(length=80), nullable=False),
    sa.Column('fields_json', sa.JSON(), nullable=False),
    sa.Column('is_fixture', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], name=op.f('fk_application_forms_job_id_job_postings'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_forms')),
    sa.UniqueConstraint('job_id', 'template_version', name=op.f('uq_application_forms_job_id'))
    )
    op.create_table('applications',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('method', sa.Enum('manual', 'assistant', 'extension', name='application_method', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'interviewing', 'offered', 'rejected', 'withdrawn', name='application_status', native_enum=False), nullable=False),
    sa.Column('applied_url', sa.String(length=2000), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mapping_version', sa.String(length=100), nullable=True),
    sa.Column('confirmation_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], name=op.f('fk_applications_job_id_job_postings'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_applications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_applications')),
    sa.UniqueConstraint('user_id', 'job_id', name=op.f('uq_applications_user_id'))
    )
    op.create_index(op.f('ix_applications_status'), 'applications', ['status'], unique=False)
    op.create_table('favorites',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], name=op.f('fk_favorites_job_id_job_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_favorites_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_favorites')),
    sa.UniqueConstraint('user_id', 'job_id', name=op.f('uq_favorites_user_id'))
    )
    op.create_table('job_posting_tags',
    sa.Column('job_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], name=op.f('fk_job_posting_tags_job_id_job_postings'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['job_tags.id'], name=op.f('fk_job_posting_tags_tag_id_job_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'tag_id', name=op.f('pk_job_posting_tags'))
    )
    op.create_table('resume_documents',
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], name=op.f('fk_resume_documents_profile_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_resume_documents_storage_key'))
    )
    op.create_table('form_mapping_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('form_id', sa.Uuid(), nullable=False),
    sa.Column('application_id', sa.Uuid(), nullable=True),
    sa.Column('mapping_version', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=100), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('confirmation_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], name=op.f('fk_form_mapping_records_application_id_applications'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['form_id'], ['application_forms.id'], name=op.f('fk_form_mapping_records_form_id_application_forms'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_form_mapping_records_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_form_mapping_records'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('form_mapping_records')
    op.drop_table('resume_documents')
    op.drop_table('job_posting_tags')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_applications_status'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('application_forms')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_job_postings_title'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_status'), table_name='job_postings')
    op.drop_index('ix_job_postings_salary', table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_posted_at'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_job_type'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_deadline'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_company'), table_name='job_postings')
    op.drop_index('ix_job_postings_city_type_deadline', table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_city'), table_name='job_postings')
    op.drop_table('job_postings')
    op.drop_index(op.f('ix_crawl_runs_status'), table_name='crawl_runs')
    op.drop_table('crawl_runs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_job_tags_name'), table_name='job_tags')
    op.drop_table('job_tags')
    op.drop_table('job_sources')
    # ### end Alembic commands ###
